nbc-SpaceS/seoul-public-service

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/example/seoulpublicservice/seoul/SeoulApiService.kt
app/src/main/java/com/example/seoulpublicservice/seoul/SeoulDto.kt
app/src/main/java/com/example/seoulpublicservice/seoul/SeoulPublicRepository.kt
app/src/main/java/com/example/seoulpublicservice/ui/notifications/NotificationsFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/notifications/NotificationsViewModel.kt
app/src/main/java/com/example/seoulpublicservice/usecase/GetAllFirst1000UseCase.kt
app/src/main/res/layout/fragment_notifications.xml
app/src/main/res/xml/network_security_config.xml

서울공공 API Service, DTO, Repository
의존성 주입을 위한 앱컨테이너
종합으로 첫 천개 가져오는 유즈케이스
-설명
GetAllFirst1000UseCase 객체를 생성해서 사용할 수 있습니다.
invoke로 만들어놨으니 객체 변수를 함수처럼 사용하면 됩니다.
Notification 프래그먼트에 예시로 작성해놨습니다.
천개 받아놓고 랜덤으로 하나 띄우게끔 했습니다.

feat: 서울공공api 구현

---

.gitignore
.idea/deploymentTargetDropDown.xml
.idea/gradle.xml
.idea/migrations.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/seoulpublicservice/InterestCategorySelectActivity.kt
app/src/main/java/com/example/seoulpublicservice/SelectCategoryService1Dialog.kt
app/src/main/java/com/example/seoulpublicservice/SelectCategoryService2Dialog.kt
app/src/main/java/com/example/seoulpublicservice/SelectCategoryService3Dialog.kt
app/src/main/java/com/example/seoulpublicservice/SelectCategoryService4Dialog.kt
app/src/main/java/com/example/seoulpublicservice/SelectCategoryService5Dialog.kt
app/src/main/java/com/example/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/res/color/selector_custom_checkbox_text.xml
app/src/main/res/drawable/background_radius_10dp.xml
app/src/main/res/drawable/background_radius_10dp_828282.xml
app/src/main/res/drawable/background_radius_10dp_dfdfdd.xml
app/src/main/res/drawable/background_radius_10dp_ffcccc.xml
app/src/main/res/drawable/background_radius_10dp_upper_f8496c.xml
app/src/main/res/drawable/background_radius_15dp_828282.xml
app/src/main/res/drawable/ic_example.xml
app/src/main/res/drawable/selector_custom_category_checkbox.xml
app/src/main/res/drawable/selector_custom_region_checkbox.xml
app/src/main/res/drawable/selector_okay_button.xml
app/src/main/res/layout/activity_interest_category_select_acitivty.xml
app/src/main/res/layout/dialog_select_category_service1.xml
app/src/main/res/layout/dialog_select_category_service2.xml
app/src/main/res/layout/dialog_select_category_service3.xml
app/src/main/res/layout/dialog_select_category_service4.xml
app/src/main/res/layout/dialog_select_category_service5.xml

변경사항의 상세 정보를 작성해주세요.
-기능
사용해볼 수 있게 관심 카테고리 선택 액티비티를 첫화면으로 세팅해놓음
대분류 버튼을 눌렀을 때 각각 다이얼로그 생성
다중 선택 가능한 체크박스 구현
-설명
관심 카테고리 선택 액티비티와 세부 카테고리 선택 다이얼로그 레이아웃 5개 만듬
대분류 버튼을 눌렀을 때 각각 다이얼로그 잘 동작하는 것 확인
체크박스를 관리하기 위한 좋은 방법은 생각해봐야할 듯
관심지역과 카테고리를 다중 선택 가능하도록 체크박스 커스텀하여 구현

[ layout ] : 관심 카테고리 선택 액티비티와 세부 카테고리 선택 다이얼로그 레이아웃

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/seoulpublicservice/MainActivity.kt
app/src/main/java/com/example/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/example/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/example/seoulpublicservice/ui/notifications/NotificationsFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/notifications/NotificationsViewModel.kt
app/src/main/java/com/example/seoulpublicservice/usecase/GetAllFirst1000UseCase.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml

전역 변수로 나와있던 컨테이너를 애플리케이션 클래스에 넣음.
뷰모델 팩토리에서 애플리케이션에 접근해서 컨테이너 안의 유즈케이스를 뷰모델의 인자로 넘겨줌.

refactor: DI 개선

---

app/src/main/java/com/example/seoulpublicservice/dialog/filter/FilterFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/map/MapViewModel.kt
app/src/main/res/drawable/ic_filter.xml
app/src/main/res/layout/fragment_map.xml

-기능
필터 적용하기 버튼을 눌렀을 때 지도 프래그먼트에서 Room DB에 쿼리 보내는 기능
-설명
Room 쿼리에 이상한 오류가 있어서 아직 결과를 보지는 못 했음
필터 적용하기를 누르면 람다식으로 만들어놓은 함수가 지도 프래그먼트에서 실행되고 거기 안에는 SharedPrefernce에 접근해 데이터를 가져오고 가져온 데이터를 가지고 쿼리를 날리는 함수가 추가되어있음
데이터를 받아오는 건 코루틴을 사용하여 했고 IO 디스패처로 진행
setValue로 LiveData에 값을 넣으려니까 에러가 나서 백그라운드에서 값을 넣는 postValue로 변경

[ Feat ] : 필터 적용하기 버튼을 눌렀을 때 지도 프래그먼트에서 Room DB에 쿼리 보내는 기능 

---

app/src/main/java/com/example/seoulpublicservice/MainActivity.kt
app/src/main/java/com/example/seoulpublicservice/seoul/SeoulDto.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageSavedAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageViewModel.kt
app/src/main/res/drawable/corners_round.xml
app/src/main/res/drawable/pencil.xml
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/layout/my_page_item_profile.xml
app/src/main/res/layout/my_page_item_reviewed.xml
app/src/main/res/layout/my_page_item_reviewed_header.xml
app/src/main/res/layout/my_page_item_saved.xml
app/src/main/res/menu/bottom_nav_menu.xml
app/src/main/res/navigation/mobile_navigation.xml

멀티뷰타입 구현하면서 sealed interface랑 CommonViewHolder도 어댑터에 집어넣었습니다.
클릭 리스너 람다식 넘겨주는건 아직 안했습니다.

MyPage 레이아웃, 멀티뷰타입 구현

---

app/src/main/java/com/example/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/example/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/example/seoulpublicservice/usecase/GetAll2000UseCase.kt
app/src/main/java/com/example/seoulpublicservice/util/RoomRowMapper.kt

앱클래스에서 시작과 동시에 데이터 불러오게끔 함.
룸 저장 3분 이내면 룸에서 꺼내오고, 아니면 통신해서 받아와서 갱신.
데이터 필터링은 현재 적용되지 않았음.
따로 유즈케이스 만들어서 필터링할 예정.

feat: 앱클래스에 rowList 만듦. GetAll2000UseCase는 현재 빈리스트 반환

---

app/src/main/res/layout/dialog_edit_profile.xml

-기능
프로필 편집 다이얼로그 레이아웃 만듬
-설명
둥근 모서리를 가지는 레이아웃
현재는 이름만 수정가능하도록 EditText 들어가 있음

[ Layout ] : 프로필 편집 다이얼로그 레이아웃

---

app/src/main/java/com/example/seoulpublicservice/seoul/SeoulPublicRepository.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/EditProfileDialog.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageSavedAdapter.kt
app/src/main/java/com/example/seoulpublicservice/util/StringExpandFuncion.kt

feat: 마이페이지 일단 랜덤으로 가져와 정보 띄워놓음 + 편집 다이얼로그

---

app/src/main/java/com/example/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/example/seoulpublicservice/db_by_memory/DbMemoryRepository.kt
app/src/main/java/com/example/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/example/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/map/MapViewModel.kt

feat: DbMemoryRepository - 다중필터링

---

app/src/main/java/com/example/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/example/seoulpublicservice/pref/SavedPrefRepository.kt

feat: SavedPrefRepository

---

app/src/main/java/com/example/seoulpublicservice/db_by_memory/DbMemoryRepository.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageSavedAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageViewModel.kt
app/src/main/res/layout/my_page_item_saved.xml

- [x ] 커밋메세지 규칙을 따릅니다.
제곧내
그리고 저장된 svcid로 정보 띄워야하니까 DbMemoryRepository에 svcid로 정보 불러오는 것도 만들었습니다.
findBySvcid 입니다.

feat: 마이페이지 저장목록 불러와 띄우기, 전체삭제 기능

---

app/src/main/java/com/example/seoulpublicservice/databases/ReservationRepository.kt

-기능
Repo의 getFilter 함수에 isEmpty 조건식 추가
-설명
조건식 추가

HOTFIX! : query 조건 추가

---

app/src/main/java/com/example/seoulpublicservice/pref/SavedPrefRepository.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageViewModel.kt

SavedPrefRepository 메서드 rename, 순서 변경

---

app/src/main/java/com/example/seoulpublicservice/db_by_memory/DbMemoryRepository.kt

필터링 - "시외" 또는 "서울제외지역"으로 날리면 서울 외 지역 검색됨

---

app/src/main/res/layout/fragment_filter.xml

Layout : 서울제외지역 버튼 활성화

---

app/src/main/java/com/example/seoulpublicservice/InterestRegionSelectActivity.kt
app/src/main/java/com/example/seoulpublicservice/MainActivity.kt
app/src/main/java/com/example/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/res/drawable/background_white_with_stroke.xml
app/src/main/res/layout/fragment_home.xml

-기능
스피너 제작해서 관심 지역 저장 및 불러오기 기능
-설명
레이아웃과 TextView의 조합으로 만들어짐
registerForActivityResult 함수 사용

[ Layout ] : 지역 선택 스피너 커스텀으로 제작

---

app/src/main/java/com/example/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/example/seoulpublicservice/SplashActivity.kt

비동기 처리 고민한다고 신경 좀 썼습니다.
스플래시 건드렸는데 설마 그 사이에 작업 안하셨겠죠...?

feat: 스플래시 화면에서 데이터 갱신이 끝나고 넘어가도록 보장

---

app/src/main/java/com/example/seoulpublicservice/db_by_memory/DbMemoryRepository.kt

feat: 필터링 - 지역 포함되면 빈거 제외

---

app/src/main/java/com/example/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/example/seoulpublicservice/pref/SavedPrefRepository.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageViewModel.kt

앱 클래스에서 데이터 갱신할 때 인터넷 연결 확인해서 안되면 바로 DB에서 꺼내게 함.
데이터 갱신할 때에도 try catch와 시간제한 걸어서 6초 내로 안되거나 에러 발생하면 DB에서 꺼내게 함.
SavedPrefRepository 기존 pref에 계속 읽기 쓰기 하던 구조에서 LiveData를 사용해서 성능 향상

인터넷 안되면 DB, API 통신 시간제한, SavedPrefRepository 리팩토링

---

app/src/main/java/com/example/seoulpublicservice/dialog/filter/FilterFragment.kt
app/src/main/java/com/example/seoulpublicservice/dialog/filter/FilterViewModel.kt
app/src/main/res/layout/fragment_filter.xml

-기능
필터페이지 우측 상단의 초기화 버튼 활성화 제어
-설명
필터 옵션을 선택한 게 하나라도 있으면 버튼이 활성화되도록 코드 추가
저장소에 저장된 것을 비교하기도 하고 현재 선택한 옵션들을 비교하기도 함
모든 케이스에서 원하는대로 작동할 수 있게 LiveData를 적극활용함

[ Feat ] : 초기화 버튼 활성화 제어

---

app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/example/seoulpublicservice/ui/mypage/MyPageSavedAdapter.kt
app/src/main/java/com/example/seoulpublicservice/util/loadWithHolder.kt
app/src/main/res/drawable/ic_loading.xml

-기능
이미지뷰에 loadWithHolder 확장함수 추가.
ic_loading 파일 추가.
-설명
코일이 이미지를 로딩하는 동안은 ic_loading 이미지를 표시하고, 로딩에 실패하거나 이미지가 없거나 하면 place_holder_1 이미지를 표시함.
url로 이미지를 받아오는 경우 이 확장함수를 사용하시기를 권장합니다.

feat: loadWithHolder

---

app/build.gradle.kts
app/google-services.json
build.gradle.kts

-기능
앱과 파이어베이스 연결 성공
-설명
말그대로 연결만 시켜놓은 것이기 때문에 이제부터 경로 만들고 키만들고 데이터 집어넣고 꺼내는 코드를 작성해야한다.

[ Feature ] : 앱과 파이어베이스 연결 성공

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/FBRef.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/ReviewEntity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/ReviewRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserEntity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapViewModel.kt

-기능
ReviewRepository, UserRepository 생성
-설명
파이어베이스 데이터베이스에 접근할 수 있는 Repository 생성
각각의 Repository에서는 Entity에 맞게 데이터를 저장하거나 가져올 수 있다.
파이어베이스 데이터베이스 함수들을 기본적으로 비동기함수이기 때문에 뷰모델에서 값을 저장할 때 postValue로 값을 저장했다.
사용예시는 MapFragment의 93~97번째 줄을 보면된다.(한번에 다 돌리면 아마 동작이 이상할 수도 있으니 테스트하고 싶은 거 하나씩 해보는 걸 추천)
상세페이지 완성되고 후기 작성공간이 생기면 그 쪽에 추가될 예정이다.

[ Feat ] : 파이어베이스 앱 연동

---

.gitignore

깃헙에서 레포 생성할 때 android로 설정하면 생성되는 gitignore 파일 내용 추가

docs: gitignore update

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/InterestRegionSelectActivity.kt
app/src/main/res/layout/fragment_home.xml

-기능
관심지역리스트 업데이트
-설명
setResult가 없어서 관심지역 리스트가 갱신되지 않았음
텍스트 색깔을 다 검은색으로 바꾸면서 얘네들도 영향을 받아 기본 텍스트 색을 따로 지정해줌

[ Fix ] : 관심지역선택 액티비티에서 빠져있던 setResult 추가

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageSavedAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageViewModel.kt

feat: 마이페이지에서 상세페이지 연결

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt

feat: 상세페이지 좌표 정보 없을 때 처리 필요

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailCommentAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailViewModel.kt

-기능
유저가 작성한 리뷰 리스트를 받아오는 함수 추가
-설명
UserRepository에 getReview 함수 추가
유저ID를 넣으면 ReviewEntity 리스트 형태로 반환됨

[ Feature ] : 파이어베이스 접근 함수 추가

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/pref/SavedPrefRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapDetailInfoAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapViewModel.kt

feat: SavedPrefRepository contains 메서드 추가 (라이브데이터에 직접 contains 하던 코드들 수정)

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/MainActivity.kt

gps 권한 없는 상태의 첫 실행 시에는 초기 위치 설정이 안됨...

feat: 초기 위치 갱신

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/ReviewRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/dialog/review/ReviewAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/dialog/review/ReviewFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/dialog/review/ReviewViewModel.kt
app/src/main/res/drawable/ic_revise.xml
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/fragment_review.xml
app/src/main/res/layout/item_detail_comment.xml
app/src/main/res/values/colors.xml

-기능
필요한 리뷰 기능
-설명
후기 작성 페이지이자 후기 리스트를 볼 수 있는 페이지로 이동간으한 더보기 버튼 생성
후기 작성 페이지에서 후기 없는 경우에 대한 예외처리 추가 -> '작성된 후기가 없습니다.' 라는 TextView 띄워줌
후기 작성 페이지에서 상세페이지로 나왔을 때 상세 페이지의 후기리스트 업데이트 기능 추가 -> 후기 작성 페이지에서 썼던 함수 그대로 사용함
한 사람이 한 서비스에 대한 후기를 한번만 작성할 수 있도록 하는 기능 추가(수정은 UI와 EditText의 hint로 인식해 자연스럽게 가능) -> 같은 곳에서 후기를 계속 쓰면 자기가 작성한 댓글이 계속 수정되는 걸 볼 수 있음
후기 아이템 레이아웃 수정(아이콘은 작게, 이름은 굵게) -> 아래에 선도 추가

[ Feat ] : 리뷰 기능 보완

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/ReviewedData.kt

feat: 마이페이지 댓글단글

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/SplashActivity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/loadWithHolder.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/util_yj.kt

-기능
String.fromHtml, String.parseColor 확장함수 추가
loadWithHolder 로딩중 이미지랑 에러 이미지 변경할 수 있도록 개선
마이페이지 유저 정보 띄우기
앱클래스에 내 유저 정보 변수 만들어둠 (스플래시에서 갱신)

마이페이지 유저 정보 띄우기

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/MainActivity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapDetailInfoAdapter.kt
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/item_map_info_window.xml

-기능
디테일 페이지, 지도 페이지 
-설명
1. 디테일 페이지 설명 공간 백그라운드 변경
둥근 모서리 사각형으로 변경
2. 검색창 비활성화
현재 할수없는 기능이므로 비활성화시킴
3. 저장 업데이트
이전에 코드로 해결된 줄 알았던 기능이 버그가 나서 emptyList를 어댑터에 넣어주는 것으로 다시 보완

[ Layout & Fix ] : 레이아웃 수정, 버그 수정

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/EditProfileDialog.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt

[ Style ] : 비공개 테스트 전 마지막 PR

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/ServiceRepository.kt

feat: getServiceReviewsCount 리스트로 받아서 병렬처리

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/pref/RecommendPrefRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

-기능
<!!!작성부분!!!>
-설명
async awaitAll 활용하여 진행함
이후에 매핑하는 것도 레포지토리에서 할 예정

[ Fix ] : 추천 페이지 과부화 문제 완화

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt

fix: GPS 권한 없을 때 지도페이지 들어가면 권한 요청하면서 멈춰버리는 문제 해결

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt

fix: 상세페이지 GPS 권한 없을 때 들어가면 권한 요청하면서 멈춰버리는 문제 해결

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/ReservationDAO.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/ReservationRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt
app/src/main/res/color/selector_detail_button_text.xml
app/src/main/res/drawable/background_detail_button.xml
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/fragment_home.xml

-기능
전화번호가 없을 시 버튼 비활성화
getAll 함수 변경
코드가 같은 xml파일 삭제함
-설명
전화번호가 없을 시 버튼 비활성화
getAll 함수가 좌표값이 빈칸이 아닌 값들을 가져오는 방식으로 변경
코드가 같은 xml파일이 2개라 상세페이지에서 사용하던 파일을 삭제함

Layout : 상세페이지 레이아웃 수정

---

app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/my_page_item_reviewed.xml
app/src/main/res/layout/my_page_item_reviewed_header.xml
app/src/main/res/values/themes.xml

design: 탭레이아웃 auto, 마이페이지 ui 약간

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt
app/src/main/res/layout/my_page_item_saved.xml
app/src/main/res/layout/recommendation_item.xml

추천아이템 레이아웃에 기본 이미지 플레이스홀더 넣음.
추천페이지에 기본적으로 들어가는 아이템 하나로만 들어가던거 다르게 넣어줌.

design: 추천아이템 이미지 플레이스홀더 넣음

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/detail/DetailFragment.kt
app/src/main/res/layout/fragment_detail.xml

-기능
후기값이 없는 것에 대한 안내 문구
-설명
TextView 만들고 데이터베이스에서 후기 값이 없는 경우에만 보이도록 구현

Layout : 상세페이지 작성된 후기가 없습니다.

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/db_by_memory/DbMemoryRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/usecase/SearchServiceDataOnMapUseCase.kt
app/src/main/res/layout/fragment_map.xml

-기능
지도 페이지 검색 기능
-설명
용제님이 만들어두신 필터함수를 변형하여 함수를 만들어 사용함
이전에 문제가 있었던 onResume 부분이 해결됨
라이브데이터를 플래그로 쓸 때 생기는 예상외 상황으로 판단
그냥 플래그를 라이브데이터로 따로 두지 않고 프래그먼트에서 함수로 만들어 사용하는 것이 해결책이었음

[ Feat & Refactor ] : 지도 페이지

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt
app/src/main/res/layout/my_page_item_reviewed_nothing.xml
app/src/main/res/layout/my_page_item_saved.xml

저장한 서비스 없음은 전체삭제에 즉각 반영이 안되긴 함

Mypage 아이템 없음 표시

---

app/build.gradle.kts

chore: minSdk 31->28

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailFragment.kt

-기능
상세 페이지의 지도부분이 깜빡이는 현상 수정
-설명
넹

Fix : DetailFragment 지도 이미지 수정

---

app/build.gradle.kts

chore: versionCode2, versionName 1.0.1

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/FBRef.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserProfileRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firebase/UserRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt

-기능
스토리지 이미지 업로드
-설명
suspend 함수
제대로 업로드가 됐다면 다운로드 url(액세스토큰)을 String 타입으로 반환
에러가 생겼다면 빈 String을 반환
한번 이렇게 스토리지 저장하고 나면 유저 데이터베이스에 저장될 거니까 다른 함수는 만들지 않음
프로필 이미지를 변경해도 덮어써질 예정
테스트는 코드가 없어서 따로 하지 못함...

[ Feat ] : 스토리지 이미지 업로드 레포지토리

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapViewModel.kt

-기능
지도 페이지 기능 안정화
-설명
외부 앱 페이지 다녀오는 경우 작동하지 않는 기능(상세정보창 정보 업데이트) 되살림
의미없어진 라이브데이터 초기화하던 거 제거
필터 페이지 넘어갈 때와 검색창 눌렀을 때 카메라 줌이 움직이던거 없앰
뭔가 라이브데이터 안에서 라이브 데이터 조절할 떼 문제가 생기는 거 같은 느낌이 강함...(특히 그냥 postValue 의심스러움)

[ Refactor ] : 지도 페이지 로직 수정

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt

feat: 마이페이지 아이템 없음 표시 즉각 반영

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt

Fix : 빠진 코드 추가

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/MyPageFragment.kt

-기능
후기 업데이트
-설명
onResume으로 다른 페이지를 잡고
공유뷰모델로 저장한 공공서비스를 잡았다.

[ Fix ] : 다른 페이지에서 후기를 작성하고 오든지 마이페이지 저장한 공공서비스에서 작성하고 오든지 바로 업데이트 되도록 변경

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/data/Item.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/CultureEventFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/EducationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/FacilityFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/FacilityRentFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/MedicalFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/MainViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/adapter/ItemAdapter.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/recommendation_item.xml

-기능
관심지역에 카테고리에 맞는 서비스가 없으면 버튼 비활성화
-설명
공유뷰모델과 ListAdapter를 이용해서 해결
dbMemoryRepository를 사용함
Item 데이터 클래스에 count 변수를 추가함
count가 0일 때는 버튼 비활성화
(예외: 앱 첫 실행시에는 관심지역이 없기 때문에 다 활성화시켜놓고 관심지역을 선택하도록 유도)
뷰페이저의 양쪽 범위를 2로 넓힘(중앙에 있을 때 좌우 2개씩 그려져있음)
클릭리스너는 null을 주면 제거되더라

[ Feat ] : 관심지역에 맞춰서 서비스 존재유무 확인 기능

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailCommentAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/dialog/review/ReviewAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/usecase/GetReviewListUseCase.kt
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/item_detail_comment.xml

-기능
후기 리스트 보여지는 것 관련해서 처리
-설명
ReviewItem에 프로필 이미지가 있을 시 프로필 이미지를 띄워주기(로딩 시간이 좀 있음...)
상세 페이지에서는 후기가 최대 5개까지 뜨도록 하기
후기는 최신순으로 나열시켜주기
프로필 이미지 영역 배경 추가

[ Feat ] : 후기 리스트 관련 기능 추가

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/data/ItemRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/CultureEventFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/EducationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/FacilityFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/FacilityRentFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/MedicalFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/adapter/ItemAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/adapter/SearchHistoryAdapter.kt

-기능
코드 정리, 임포트 문 정리, 안쓰는 변수 및 주석처리된 함수 정리
-설명
코드정리, import문 간소화, 주석 처리된 부분 1개빼고 전부 삭제

코드 정리, Import 문 정리, return 문 간소화

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt
app/src/main/res/layout/fragment_home.xml

-기능
MVVM !
-설명
레포지토리를 사용하여 데이터를 받아오는 코드는 다 ViewModel로 넘김
그리고 프래그먼트에서는 UI 갱신만 할 수 있게 함
넘어간 부분은 관심지역 선택, 검색, 최근 검색어 기능이다.
(추가로 최근 검색어창이 검색창 아래로 가게 검색창에 elevation을 1dp 주고 그림자 색을 없애버렸다.)

[ Refactor ] : 홈 프래그먼트 MVVM 패턴 적용

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/category/CategoryFragment.kt

-기능
키보드 사라짐!
-설명
EditText를 제외한 나머지 부분 클릭 시 키보드 사라짐
키보드로 확인 버튼 눌러도 사라짐 야호!

Feat : EditText 외부 터치 시, 키보드 확인버튼 클릭 시 키보드 사라짐

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/adapter/HomeSearchAdapter.kt

-기능
메인 페이지에서 상세 페이지로 넘어감
-설명
메인에서 검색하고 나온 결과 아이템 클릭시 상세페이지로 넘어가는 코드 추가

Feat : 메인 페이지에서 검색된 결과를 클릭할 때 상세 페이지로 넘어가는 코드 추가

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/res/layout/fragment_home.xml

-기능
검색어 창 포커스 풀리게 하고 저장된 검색어 창 닫게 하기
-설명
검색어 창 밖을 터치시 검색어 창 포커스 풀리게 하고 저장된 검색어 창이 닫히게 만들었습니다

검색창 이외의 화면을 클릭시 검색창 포커스를 없애고, 저장된 검색어 창 닫게 하

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt

!HOTFIX : 터치 리스너 버그 발생해서 일단 주석처리

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt

-기능
홈화면 코드 리팩토링 + 메모리 누수 방지용 Destroy추가
-설명
MainViewModel을 관찰하는 코드와 HomeViewModel을 관찰하는 코드를 initViewModel()에 모으고, 홈 화면이 안보일 때 메모리 누수 방지하는 것을 막기 위해 끝에 onDestroyView 메소드를 추가하였다. 맞겠지? ㅠㅠ

Refactor : 뷰모델 관련 코드 initViewModel() 에 통합, onDestroyView()를 추가해서 홈화면이 안보일 떄 메모리 누수 방지용으로 메소드 만듦, import 문 정리

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/main/MainActivity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt

refactor: FusedLocationSource를 앱클래스에 올려서 전역화

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt

약간 다듬었습니다.
이 구조로 기상청 api 단기랑 중기 얹으면 될 것 같습니다.

style: AppContainer에 retrofit 관련 코드 정리

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/ComplaintRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/UserBanRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/UserProfileRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/FacilityFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/usecase/GetReviewListUseCase.kt

-기능
코드 포맷 변경, 조건 추가, 코드 제거
-설명
"다목적 경기장"으로 쿼리를 날리면 값이 안 오고 "다목적경기장"으로 날려야 값이 들어오더라...
메인 페이지의 있는 서비스들을 알려주는 텍스트의 spannableString의 범위를 선택한 구의 글자 길이에 따라 변하도록 추가 -> 길이가 2,3이면 그대로, 길이가 4면 +1을 해서 실행하도록 함
안 쓰는 코드 통째로 삭제(이미지 업로드 쪽 레포지토리 함수)

[ Style ] : 코드 포맷 변경, 안 쓰는 코드 제거

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/UserRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/seoul/SeoulApiService.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/seoul/SeoulPublicRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/mypage/EditProfileDialog.kt
app/src/main/res/drawable/selector_edit_profile_okay_background.xml
app/src/main/res/layout/custom_progress.xml
app/src/main/res/layout/dialog_edit_profile.xml

닉네임 변경 길이 제한, 중복 확인
서울API 전체 데이터 받아오는거 병렬처리
비동기 처리 정신 나갈거같아

Seoul api parallel

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/category/CategoryFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

Fix 플로팅 버튼 위,아래 스크롤 해도 안 없어지도록 수정.
Test 추천페이지 무한스크롤 테스트 중

카테고리 페이지 플로팅 버튼 수정

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt

-기능
날씨 주석처리함
-설명
날씨 json 어쩌구 에러가 또또또또또 발생해서 일단 주석처림

Comment : 날씨부분 주석처리함

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/res/layout/fragment_recommendation.xml

feat: 추천페이지 로딩 화면

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/db_by_memory/DbMemoryRepository.kt

좌표값 안전하게 판단하겠다고 toDoubleOrNull로 변경했는데 이거때문에 로딩이 엄청나게 느려질 줄은 몰랐다.
다시 isNotBlank로 돌려놓음.
hasLocation 로직을 바꿀 필요가 있을 듯. toDoubleOrNull로 위치값 있는 애들만 따로 변수 만들어놓으면 괜찮을듯.

fix: 홈화면 로딩 느려지는 문제: hasLocation을 toDoubleOrNull로 했더니 느려짐

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/db_by_memory/DbMemoryRepository.kt
app/src/main/res/layout/fragment_home.xml

-기능
랜덤 배너 정상 작동
-설명
서비스 접수 상태(SVCSTATNM)가 들어가야하는 부분에 서비스 이름(SVCNM)이 들어가있었다...
분명 날짜 범위 체크할 때 다 true 나오는데 왜그런가 싶었다...

[ Fix ] : 조건에 맞는 서비스가 있음에도 랜덤 배너 작동 안 하는 문제

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationHorizontalData.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

MultiView.Horizontal이 검색 키워드를 들고 있어야 무한스크롤 할 때 어떤 키워드로 메서드를 호출할 건지 정할 수 있어서 추가해줌. 파라미터 추가된 거에 맞춰서 프래그먼트에서 멀티뷰 만들 때랑 뷰모델에서 RecommendationHorizontalData 만들 때에도 키워드 넣어줌.

refactor: 추천페이지 가로 무한스크롤 뷰쪽 코드 수정

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midLandFcst/MidLandFcstApiService.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midLandFcst/MidLandFcstDto.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midLandFcst/MidLandFcstRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempApiService.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempDTO.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt

-기능
핫픽스? : 중기기온, 중기예보 Repository 수정
-설명
HomeViewModel에서 날씨 데이터 받는 부분( fetchWeatherData ) 코드 수정

Fix : Repository 코드 변경

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt

HOTFIX! : 날씨 진짜 진짜 진짜 수정했어요 ㅠㅠ

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/notifications/NotificationsFragment.kt
app/src/main/res/layout/fragment_recommendation.xml
app/src/main/res/layout/recommendation_item.xml
app/src/main/res/layout/recommendation_item_recommended.xml
app/src/main/res/layout/recommendation_item_recommended_tip.xml

-기능
알림 기능 복구
추천 페이지 UI 수정
-설명
제발 무의식적으로 하는 알림 페이지 삭제를 멈춰주세요...
이미지 크게!
마진 넓게!!
부가 설명은 한 줄에!!!

[ Fix & Layout ] : 사라져있던 알림 페이지 코드 복구, 추천 페이지 아이템 레이아웃 변경

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempApiService.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempDTO.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/kma/midTemp/MidTempRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/weather/WeatherApiService.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/weather/WeatherShortDTO.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/weather/WeatherShortRepository.kt

날씨 API 예외처리 완료

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/ServiceRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationAdapter.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

-기능
추천 페이지 가로 무한 스크롤
-설명
추가 데이터 불러오는 것과 리사이클러뷰에 세팅하는 것
인덱스 넘어갈 때 체크하는 것과 지역 변경됐을 때 적용하는 것
중첩 리사이클러뷰는 상당히 힘들었다...
map과 adapter, submitList 관련해서 좀 뭔가 알게 되었다.

[ Fix ] : 가로 무한 스크롤 기능

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt

-기능
코드 스타일만 약간 수정됨
-설명
주석 설명이 잘못 된 부분 변경
HomeViewModel ctrl + alt + L 사용해서 포매팅 진행되버림

[ Style ] : 주석 변경, 코드 포매팅

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt

-기능
Room 접근 에러
-설명
이전에 코루틴으로 감쌌던 부분을 빼고 진행했었는데 갑자기 푸시받고 나니까 이 부분이 문제인듯? Room 접근을 비동기로 안 해서 그런 거 같다

[ Fix ] : HomeViewModel에서 Room 접근할 때 앱 터지는 문제

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

-기능
무한 스크롤 버그
-설명
뭔가뭔가 추가 이미지가 이전 이미지를 먹어버리는 버그, 데이터는 한참 많은데 한번만 추가 데이터를 받아오는 버그가 나서 잡았는데 이미지 로딩 버그가 해결되고 나니까 괜찮아져서 추천 페이지 지역 선택 쪽 다시 그릴 때 dataList 값 변경 부분만 건드림

[ Fix ] : 무한 스크롤 버그

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/SeoulPublicServiceApplication.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/map/MapFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/usecase/LoadAndUpdateSeoulDataUseCase.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/loadWithHolder.kt

지도 현위치 서울인지 확인

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/databases/firestore/WeatherDBRepository.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/di/AppContainer.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/home/HomeViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/weather/WeatherShort.kt

-기능
서버 캐싱
-설명
특정 지역에 대한 날씨 데이터가 서버에 있을 때는 서버에서 가져오고 없을 때는 API 통신을 해서 가져온 다음 서버에 저장하도록 구현
서버에 있지만 업데이트 시간이 현재 시간보다 1시간 전이라면 없을 때와 동일하게 API 통신을 해서 가져온 다음 서버에 저장하도록 구현
서버에서 데이터를 가져온 경우에는 업데이트 시간을 최신화하지 않도록 구현

[ Feat ] : 날씨 데이터 서버에 캐싱

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/DLog.kt

debug 빌드에서만 로그를 찍고 싶다면 Log 앞에 D만 붙여 사용하면 됩니다.
배포되는 release 버전에서는 로그를 안찍기 때문에 로그를 찍는 약간의 오버헤드가 사라집니다.  
구현에 따라서는 로그를 찍기 위한 데이터 가공에서부터 `if (BuildConfig.DEBUG) {}` 를 할 수도 있는데  
이런 경우는 해당 블록이 이미 디버그 모드에서만 동작하므로 중복해서 DLog를 사용할 필요가 없습니다.

feat: DLog 유틸 구현

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/SplashActivity.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/usecase/LoadAndUpdateSeoulDataUseCase.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/util_yj.kt

fix: 네트워크 x, 룸 x -> 종료

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt

fix: 추천페이지 터지는거 수정

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/recommendation/RecommendationViewModel.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/util/loadWithHolder.kt
app/src/main/res/drawable/place_holder_3.xml

fix - 추천페이지 take(4)로 맞춰줌

---

app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailFragment.kt
app/src/main/java/com/wannabeinseoul/seoulpublicservice/ui/detail/DetailViewModel.kt

-기능
상세페이지 거리제한 해제
-설명
구글 ~ 서울 = 9030? km

Fix : 상세 페이지 거리제한 해제
